services:
  # 1. Backend Web Service
  - type: web
    name: hirehub-api
    runtime: docker
    dockerfilePath: hirehub-backend/Dockerfile
    dockerContext: hirehub-backend
    plan: free
    envVars:
      - key: DB_URL
        value: "jdbc:postgresql://db.yfbgidketrdfxobaklsx.supabase.co:5432/postgres"
        sync: false
      - key: DB_USERNAME
        value: postgres
      - key: DB_PASSWORD
        value: "Vwewa54ZS5bX7PsO"
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRATION_MS
        value: "900000"
      - key: JWT_REFRESH_EXPIRATION_MS
        value: "604800000"

  # 2. Frontend Web Service
  - type: web
    name: hirehub-frontend
    runtime: docker
    dockerfilePath: hirehub-app/Dockerfile
    dockerContext: hirehub-app
    plan: free
    envVars:
      - key: BACKEND_URL
        fromService:
          type: web
          name: hirehub-api
          envVarKey: RENDER_EXTERNAL_URL
      - key: NGINX_ENVSUBST_FILTER
        value: "BACKEND_URL"
